---
- name: Create A Pool
  bigip_pool:
    provider: "{{ provider }}"
    state: "{{ item.state | d('present') }}"
    partition: "{{ item.partition | d('Common') }}"
    lb_method: "{{ item.lb_method | d('ratio-member') }}"
    name: "{{ item.name }}"
    slow_ramp_time: "{{ item.slow_ramp_time | d(120) }}"
  loop: "{{ pools }}"
