---
- name: Create A Pool
  bigip_pool:
    provider: "{{ provider }}"
    state: present
    partition: Common
    lb_method: ratio-member
    name: Jeff-Role-Test-Import-Role
    slow_ramp_time: 120
    validate_certs: False