language: python
install:
  - pip install ansible-lint
  - ansible-lint --version
script:
  - ansible-lint *.yml 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master
