language: python
python:
  - "3.8.1"
env:
  - ANSIBLE_VERSION=latest
install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
script:
  - ansible-playbook --syntax-check build_lb.yml
  - ansible-lint
