---
- name: Build Load Balancer
  hosts: bigip_devices
  connection: local
  gather_facts: false

  vars:
    provider:
      server: "{{ansible_host }}"
      server_port: "{{ ansible_port }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      validate_certs: false

  tasks:
    - import_role:
        name: create_pools