---
- name: Build Load Balancer
  hosts: bigip_devices
  connection: local

  vars:
    provider:
      server: "{{ bigip_server }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"

  tasks:
    # - include_role:
    name: create_pools
    #   tasks_from: create_pools
    - import_role:
        name: create_pools
