---
- hosts: bigip_devices
  connection: local
  tasks:
  - set_fact:
      provider:
        server: "{{ bigip_server }}"
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
  - name: Create A Pool
    bigip_pool:
      provider: "{{ provider }}"

      state: present
      partition: Common
      lb_method: ratio-member
      name: Jeff-Web02
      slow_ramp_time: 120
      validate_certs: False